# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tips', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='article_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('pub_date', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.article_list'),
        ),
    ]
